Executable samples to export
smeup/jariko pull request #195
Opened 2020-10-12 12:23 UTC by parodi-smeup

## Description

Include a summary of the change.

Related to # (issue)

## Checklist:
- [ ] There are tests regarding this feature
- [ ] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [ ] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2020-10-12 14:03 UTC, lanarimarco requested changes

2020-10-12 15:03 UTC, parodi-smeup commented on examples/src/main/kotlin/com/samples/jariko/RpgSamples.kt
> +/**
done

2020-10-12 15:03 UTC, parodi-smeup commented on examples/src/main/kotlin/com/samples/jariko/RpgSamples.kt
> +
done

2020-10-12 15:04 UTC, parodi-smeup commented on examples/src/main/kotlin/com/samples/jariko/RpgSamples.kt
> +
done

2020-10-12 15:04 UTC, parodi-smeup commented on examples/src/main/kotlin/com/samples/jariko/RpgSamples.kt
> +    fibonacciOf(15)
not a "main" anymore, changed to a generic callable fun with non parameres

2020-10-12 15:05 UTC, parodi-smeup commented on examples/src/main/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
removed

2020-10-12 15:05 UTC, parodi-smeup commented on examples/build.gradle
> +    manifest {
removed

2020-10-12 16:10 UTC, lanarimarco requested changes
There is a little change request in function fibonacciOf that should return the calculated number.

2020-10-12 16:10 UTC, lanarimarco commented on examples/src/main/kotlin/com/samples/jariko/RpgSamples.kt
> +                println(symbolTable["FINAL_VAL"].asInt().value)
Printing of the calculated number is not what I would. I would like the function to return the calculated number

2020-10-13 14:28 UTC, lanarimarco approved these changes
Ok

2020-10-13 14:28 UTC, merged