Fix SORTA operation code (in case of arrays and DS)
smeup/jariko pull request #272
Opened 2021-08-31 16:08 UTC by parodi-smeup

## Description

Avoid to fail 'SORTA' operation code, when it is used to order an array by its subfield (which could be considered as a substring of an element of the array). The 'sorta' operation now support 'EBCDIC' order, due to 'EBCDICComparator' implementation which works as expected in AS400 environment.
See **SORTATEST.rpgle** and **MUTE13_30.rpgle** tests.

## Checklist:
- [X] There are tests regarding this feature
- [X] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [X] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2021-09-01 09:23 UTC, lanarimarco requested changes

2021-09-02 08:36 UTC, parodi-smeup commented on rpgJavaInterpreter-core/src/main/java/com/smeup/rpgparser/utils/EBCDICComparator.java
> +    private static byte[] b1;
Ok

2021-09-02 08:39 UTC, parodi-smeup commented on rpgJavaInterpreter-core/src/main/java/com/smeup/rpgparser/utils/EBCDICComparator.java
> +            e.printStackTrace();
Ok

2021-09-02 11:05 UTC, lanarimarco approved these changes
Ok

2021-09-02 11:05 UTC, merged