Bugfix/nw23001440/check bif
smeup/jariko pull request #416
Opened 2024-02-09 14:36 UTC by cosentino-smeup

## Description
In this branch we have implemented the BIF %CHECK

Note: 
the fourth parameter has not been included:
{ : *NATURAL | *STDCHARSIZE}

Related to:
T04_A15

## Checklist:
- [X] There are tests regarding this feature
- [X] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [X] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2024-02-12 12:18 UTC, lanarimarco requested changes
When you implement a new bif (and in general it is always a good practice) you should add at least a `BIFCHECK.rpgle` test program in `rpgJavaInterpreter-core/src/test/resources` path and the related function  `InterpreterTest.executeBIFCHECK`.
The `Txx_Ayy_Pzz` tests often contain a lot of noise and it is not always clear what they  are testing.

2024-02-12 12:18 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/T04_A15.rpgle
Why not a single program per step?

2024-02-13 10:30 UTC, cosentino-smeup commented on rpgJavaInterpreter-core/src/test/resources/smeup/T04_A15.rpgle
added BIFCHECK

2024-02-13 10:42 UTC, cosentino-smeup commented on rpgJavaInterpreter-core/src/test/resources/smeup/T04_A15.rpgle
split T04_15 into 3 tests

2024-02-13 11:43 UTC, lanarimarco approved these changes
Ok

2024-02-13 11:44 UTC, merged