Feature/add dspfparser module
smeup/jariko pull request #536
Opened 2024-06-03 05:10 UTC by andraasi

## Description

Add dspfparser module

## Checklist:
- [ x] There are tests regarding this feature
- [ x] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [ x] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2024-06-03 10:59 UTC, lanarimarco requested changes
There is something to fix.

2024-06-03 10:59 UTC, lanarimarco commented on dspfparser/src/test/resources/_d2.dspf
capitalize the name

2024-06-03 10:59 UTC, lanarimarco commented on dspfparser/src/test/resources/_fake.dspf
capitalize the name

2024-06-03 10:59 UTC, lanarimarco commented on dspfparser/src/test/resources/b£1601av.dspf
capitalize the name

2024-06-03 10:59 UTC, lanarimarco commented on dspfparser/src/test/resources/b£1601bv.dspf
capitalize the name

2024-06-03 13:40 UTC, andraasi commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesclassifier/DSPFSpecifications.kt
> +internal const val SHOULD_ADD_RELATED_AND_FILE: Boolean = false
For this "switch" and the other similar in DSPFLine, I decided to simply remove them. Its purpose were to make some asserts (asserts concerning "will-come" features, that are currenlty out of scope) skip based on its values. I removed those asserts too.

2024-06-03 13:41 UTC, andraasi commented on dspfparser/src/test/kotlin/com/smeup/dspfparser/linesprocessor/KeywordsTest.kt
> +    @Test @Ignore
My fault, this was a leftover test, I removed it.

2024-06-03 13:55 UTC, andraasi commented on dspfparser/src/test/kotlin/com/smeup/dspfparser/linesclassifier/B1601av.kt
> +    fun tt() {
Forgot to add test asserts. Now added a bare minimum assertions.

2024-06-04 09:55 UTC, lanarimarco requested changes

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/build.gradle
> +            artifactId 'dspfarser'
fix typo

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesclassifier/DSPFSpecifications.kt
> +    override fun getRecord(name: String): DSPFRecordSpecifications {
Is there a test regarding this feature? I think this implementation is wrong

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesclassifier/DSPFSpecifications.kt
> +    override fun getFieldsFromRecord(name: String): MutableList<DSPFFieldSpecifications> {
Is there a test regarding this feature? I think this implementation is wrong

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesprocessor/LinesSubstringsMerger.kt
> +                line += it.line.removeLast(it.continuationChar.toString())
Concat using `line +=` could be inefficient. Replace it with `StringBuilder.append` or equivalent.

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesprocessor/LinesSubstringsMerger.kt
> +                    line += it.line.trim().removeLast(it.continuationChar.toString())
see above

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesprocessor/LinesSubstringsMerger.kt
> +                    line += it.keywords.trim().removeLast(it.continuationChar.toString())
see above

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesprocessor/LinesSubstringsMerger.kt
> +                line += it.keywords.trim()
see above

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesclassifier/DSPFFieldSpecifications.kt
> +    val related: MutableList<DSPFLine> = mutableListOf()
This property is no longer used, why?

2024-06-04 09:55 UTC, lanarimarco commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/linesclassifier/DSPFSpecifications.kt
> +    val file: DSPFFileSpecifications = DSPFFileSpecifications.create()
This property is no longer used

2024-06-05 07:48 UTC, lanarimarco approved these changes
Ok

2024-06-05 08:19 UTC, merged