Feature/data definition from dspf
smeup/jariko pull request #542
Opened 2024-06-07 11:59 UTC by andraasi

## Description

Introducing capability to load display files directly instead of using JSON metadata thanks to the integration with dspfparser module. Now`FileDefinition.toDataDefinition()` will adapt its behavior based on its `fileType` property. To be more precise, a class named `SimpleDspfConfig` implements `.getMetadata(displayFile: String)` that produces an object of type `FileMetadata` by converting a list of`DSPFField` object, obtained as parser result, to a list of `DbField` used then to produce the wanted `FileMetadata`. With such a solution jariko isn't aware of the fact that those `DbField` are part of a display file and not part of a database file, and it can continue operating with them as it usually would. `DspfConfig` is added to `Configuration` to bind the correct `metadataProducer` callback function based on `fileType`.

## Checklist:
- [x] There are tests regarding this feature
- [x] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [x] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2024-06-07 13:12 UTC, andraasi commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/domain/DSPF.kt
Property is used to access all fields (for all record) from a display file.

2024-06-07 13:17 UTC, andraasi commented on dspfparser/src/main/kotlin/com/smeup/dspfparser/domain/DSPFField.kt
If a display file field has REFFLD keyword it can have no x, y specified; see MLNGT60BV SHDEAR field.

2024-06-07 13:22 UTC, lanarimarco reviewed
In general, good, only some adjustments needed.

2024-06-07 13:22 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/interpreter/video.kt
> +            var rpgType: String
Also rpgType is immutable.

2024-06-07 13:22 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/parsing/parsetreetoast/misc.kt
> +    if (fileType == FileType.DB) return loadDbFileMetadata()
Use `when` and throw an error if `fileType` is neither `FileType.DB` nor `FileType.VIDEO`.

2024-06-07 13:22 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/testing_utils.kt
> +            dspfConfig = DspfConfig { displayFile ->
I have no information about which `displayFile` is not found. See the implementation above as an example of the correct handling.

2024-06-07 13:22 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/video/VideoInterpeterTest.kt
> +    @Test @Ignore("Will be tested further")
Why Ignore?

2024-06-07 13:22 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/video/VideoInterpeterTest.kt
> +    @Test @Ignore("Will be tested further")
Why Ignore?

2024-06-07 13:23 UTC, andraasi commented on rpgJavaInterpreter-core/src/test/resources/smeup/metadata/MLNGT60AV.dspf
Demo display file taken from AS400 to replace MLNGT60AV.json

2024-06-07 13:23 UTC, andraasi commented on rpgJavaInterpreter-core/src/test/resources/smeup/metadata/MLNGT60BV.dspf
Demo display file taken from AS400 to replace MLNGT60BV.json

2024-06-07 13:30 UTC, lanarimarco requested changes
Sorry, but I underestimated the `FileDefinition.toDataDefinitions()` implementation. It is wrong and it has too many changes.

2024-06-10 10:10 UTC, lanarimarco requested changes

2024-06-10 10:10 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/execution/SimpleDspfConfig.kt
> +            require(videoFile.exists()) { "$videoFile doesn't exist" }
Move `require` before the return statement, because here it is too late.

2024-06-10 10:18 UTC, lanarimarco approved these changes
Ok

2024-06-10 10:47 UTC, merged