Bugfix/ls24003505/move and movel with boolean type
smeup/jariko pull request #578
Opened 2024-07-26 10:41 UTC by davidepalladino-apuliasoft

## Description
This work adds the capability to use `MOVE` and `MOVEL` when the result is an indicator.
It is assumed that for blank or decimal value as Factor 2, the final value considered will be `0`.

Related to #LS24003505

## Checklist:
- [ ] There are tests regarding this feature
- [ ] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [ ] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2024-07-26 14:03 UTC, lanarimarco requested changes

2024-07-26 14:03 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/interpreter/JarikoCallbackTest.kt
> +    fun executeERROR29CallBackTest() {
For each of this test you should create `executeERRORnnSourceLineTest()`

2024-07-29 05:41 UTC, davidepalladino-apuliasoft commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/interpreter/movel.kt
> +            (valueInterpreted.isDecimal() && valueInterpreted.toDecimal() in 0.0..1.0) -> "0"
For RPG is that right. I was shocked while I was testing on AS400.

2024-07-29 05:58 UTC, davidepalladino-apuliasoft commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/interpreter/movel.kt
> +            (valueInterpreted.isInt() && valueInterpreted.toInt() in 0..1) -> if (valueInterpreted.toInt() == 0) "0" else "1"
I agree, it is a typo

2024-07-29 07:27 UTC, lanarimarco approved these changes
ok

2024-07-29 07:28 UTC, merged