Bugfix/ls24003751/elem evaluation during execution
smeup/jariko pull request #590
Opened 2024-08-07 10:17 UTC by davidepalladino-apuliasoft

## Description
This work resolves evaluation of `NumberOfElementsExpr` during execution. In the previous implementation `InternalInterpreter.execute` performed an initialization. `initialize` called `eval` for `NumberOfElementsExpr`, which called - at the end - `interpreterStatus.getVar`. In this case, `getVar` took the value from SymbolTable, that was `NullValue`. Is wrong! Is necessary the size of array. So, the fix has been performed into `eval(expression: NumberOfElementsExpr)`, by leaving evaluation by `interpreterStatus` only, at the moment, for `OccurableDataStructureType`. 

Related to #LS24003751

## Checklist:
- [ ] There are tests regarding this feature
- [ ] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [ ] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

2024-08-13 11:14 UTC, lanarimarco requested changes

2024-08-13 11:14 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00105.rpgle
Add a comment in the code to highlight where the runtime error occurred. Improve the assertion, as the current one seems too weak. The "Ok" assertion only confirms that Jariko does not crash but does not ensure that Jariko behaves correctly.

2024-08-19 06:43 UTC, davidepalladino-apuliasoft commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00105.rpgle
I decided to remove the `DSPLY` operation code because was a typo and is not necessary: without fix, with or not the `DSPLY`, there is always an runtime error. An hypothetical printing of `£40ANM` value is unnecessary because the bug is during the runtime evaluation of `£40A` parameter in `PLIST`.
So, for this reason I can't identify a strong evaluation for the Jariko behavior; I don't know how to have the evaluation result during the evaluation of that `PLIST` parameter. In this case I relied to global tests.

2024-08-19 07:04 UTC, davidepalladino-apuliasoft commented
Updated description of this PR.

2024-08-19 13:34 UTC, lanarimarco requested changes
The first part of the PR description is a bit too technical. Keep in mind that the first one or two sentences will be read by an RPGLE developer who might not have any knowledge of Jariko. Therefore, the language should be understandable to an RPGLE developer. 

Afterward, you can explain your solution in technical terms.

2024-08-19 13:34 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00105.rpgle
> +     D £40ANM          S              5S 0 INZ(%ELEM(£40A))                       Jariko Runtime Error: 'Void value for £40A' during evaluation of PLIST
A comment here where you say: "runtime error during invocation of %ELEM(£40A)" is sufficient, as I think the rest does not add much to the test understanding.

2024-08-19 13:34 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00105.rpgle
> +     D £40ANM          S              5S 0 INZ(%ELEM(£40A))                       Jariko Runtime Error: 'Void value for £40A' during evaluation of PLIST
A comment here where you say: "runtime error during invocation of %ELEM(£40A)" is sufficient, as I think the rest does not add much to the test understanding.

2024-08-19 13:34 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00105.rpgle
Why not display the content of the variable that was not initialized? Aren't you curious to see what it is?

2024-08-29 06:01 UTC, davidepalladino-apuliasoft commented
Updated description of this PR.

2024-08-29 07:49 UTC, lanarimarco approved these changes

2024-08-29 07:49 UTC, merged