Bugfix/ls24003783/array in ds inz
smeup/jariko pull request #597
Opened 2024-08-20 09:30 UTC by dom-apuliasoft

## Description

Given a DataStructure `$A` containing an array field `$B`, if `$B` was also marked with empty `INZ` keyword the system tried to initialize `$B` with a real number, throwing a runtime error.

To avoid this issue I added a check on the definition being an array during the creation process.

Related to:
- LS24003783

## Checklist:
- [x] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [x] There are tests for this feature.
- [x] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [x] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [x] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

2024-08-22 11:53 UTC, lanarimarco requested changes

2024-08-22 11:53 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/parsing/parsetreetoast/data_definitions.kt
Honestly, if your purpose was not to initialize the `initializedValue` in the case of fields declared as an array, I'm struggling a bit because the same commit includes both fixes and refactoring. Next time, maybe separate them into two commits, as it would be easier for me catching the nuances.

2024-08-22 11:53 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00249.rpgle
> +     D  £6I                          20P 6 DIM(99) INZ                          Importi
What should be the value of the elements in this array when initialized like this? You should add a stronger assertion, for instance, by testing the value of the first element of the array.

2024-08-22 13:45 UTC, dom-apuliasoft commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/parsing/parsetreetoast/data_definitions.kt
It is an oversight on my side, I was not aware I moved the code and the refactor was not intended. The only intended bit was to move `arraySizeDeclared` before the check so to be able to determine if we are considering an array or a plain value. Only now I saw the (useless) noise I generated, I apologize for that.

2024-08-26 12:47 UTC, lanarimarco approved these changes

2024-08-26 12:48 UTC, merged