Bugfix/ls24004056/packed coverage
smeup/jariko pull request #618
Opened 2024-09-25 14:46 UTC by dom-apuliasoft

## Description

This PR does not add or change any RPG language functionality

From a technical standpoint changes are:
- Addition of new test cases for PACKED value and the interoperability of DS and strings
- The removal of a check added in #600 that caused a regression in number coercion

Related to:
- LS24004056
- #600 
- #602 
- #617 

## Checklist:
- [x] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [x] There are tests for this feature.
- [x] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [x] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [x] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

2024-09-26 13:21 UTC, lanarimarco requested changes
I appreciate implementations where you cut than adding to it! 😊

In addition to my comments on specific files, it seems there's no test that follows this structure:

- Declare a `DS1` with `StringType`, `NumberType` zoned, and `NumberType` packed.
- Declare `S1`, a standalone `StringType` similar to `DS1`.
- Declare `DS2`, structured like `DS1`.
- Assign `DS1` to `S1` and then assign `S1` to `DS2`.
- Assert that each field of `DS1` is equal to the corresponding field in `DS2`.

2024-09-27 15:45 UTC, lanarimarco reviewed
I have a doubt about a test

2024-09-27 15:45 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/mute/MUTE13_41.rpgle
> +     C                   EVAL      J1DTIN=20230930
Why not `JALOGT.J1DTIN` for this fields and for all fields below?

2024-09-27 15:45 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/mute/MUTE13_41.rpgle
> +     C                   EVAL      JALOGT=SJALOG
Why not `JALOGT2=SJALOG`

2024-09-27 16:29 UTC, benetti-smeup commented on rpgJavaInterpreter-core/src/test/resources/mute/MUTE13_41.rpgle
> +     DJALOGT2        E DS                  EXTNAME(JALOGT0F) INZ
@dom-apuliasoft It’s not possible to define two data structures based on a file without renaming the fields. The fields become duplicated, and the program cannot be compiled on IBMi. You changed the example without testing that it works on IBMi.

2024-09-30 07:30 UTC, dom-apuliasoft commented
As I understand my changes to `MUTE13_41` were not appropriate I rolled it back to the original version @benetti-smeup gave me and only added the MUTE assertions in it. Let me know if it ok now and else-wise what needs to be changed.

2024-09-30 10:46 UTC, lanarimarco approved these changes

2024-09-30 10:46 UTC, merged