Bugfix/LS24004236/Indicator considered for block execution
smeup/jariko pull request #619
Opened 2024-09-30 07:03 UTC by davidepalladino-apuliasoft

## Description
This work adds the capability to consider "indicator condition" for statements as conditional or iterator. For example:
```
     C   351             IFEQ      1
     ...
     C                   ELSE
     ...
     C                   ENDIF
```
In this case if `*IN35` is `*ON` the entire block (`IFEQ` or `ELSE`, based the condition) is executed.
For this work we have considered `IFxx`, `DOUxx`, `DOWxx`, `FOR` and `DO`.

### Technical notes
Jariko didn't cover the evaluation of indicators for statements as conditional or iterator. So, I have provided to add it by consider the logic for single statement.

Related to #LS24004236

## Checklist:
- [x] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [x] There are tests for this feature.
- [x] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [x] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [x] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

2024-09-30 09:59 UTC, davidepalladino-apuliasoft commented
Converted to draft to add test related to `DOW` and `DOU`

2024-10-01 09:53 UTC, lanarimarco requested changes
Except for the code duplication, for which I ask you refactor, I think your solution is the best it could be.

2024-10-01 09:53 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/parsing/parsetreetoast/statements.kt
What you've added in `statements.kt` is almost identical to what's already present in `misc.kt`.  
![image](https://github.com/user-attachments/assets/8c43d441-6723-48d9-9caf-0d3e7ab9aa69)
You should refactor this logic into a new function to avoid duplicated code.

2024-10-01 10:16 UTC, davidepalladino-apuliasoft commented on rpgJavaInterpreter-core/src/main/kotlin/com/smeup/rpgparser/parsing/parsetreetoast/statements.kt
You are right. I forgot to refactor this one and `toIndicatorCondition` too

2024-10-01 13:00 UTC, lanarimarco approved these changes

2024-10-01 13:00 UTC, merged