Bugfix/ls24004467/dim with len
smeup/jariko pull request #637
Opened 2024-10-15 10:01 UTC by dom-apuliasoft

## Description

Given a definition `$A` defined somewhere in the program, defining a definition `$B` using `DIM(%LEN($A))` should not throw any error and define `$B` accordingly.

From a technical standpoint a new branch was added in `CompileTimeInterpreter.evaluate` to properly address `LenExpr`s.

Related to:
- LS24004467

## Checklist:
- [x] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [x] There are tests for this feature.
- [x] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [x] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [x] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

2024-10-16 09:09 UTC, lanarimarco requested changes

2024-10-16 09:09 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00265.rpgle
> +     D $SER            S              3  0 DIM(%LEN(SSERIE))
What was the error?

2024-10-16 09:09 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/resources/smeup/MUDRNRAPU00265.rpgle
> +     D STACK           DS                  OCCURS(300)
Is this DS declaration necessary?

2024-10-16 10:28 UTC, dom-apuliasoft commented
@lanarimarco I simplified the test case and moved the error description next to the erroring line.

2024-10-16 10:55 UTC, lanarimarco requested changes
Doc issue

2024-10-16 10:55 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/smeup/MULANGT02ConstAndDSpecTest.kt
> +     * Like on a definition that is defined as a field of an occurable data structure
I think that doc is not correct

2024-10-16 10:55 UTC, lanarimarco commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/smeup/MULANGT02ConstAndDSpecTest.kt
> +     * Using %LEN on a definition inside a DIM
Maybe this was the correct doc?

2024-10-16 12:10 UTC, dom-apuliasoft commented on rpgJavaInterpreter-core/src/test/kotlin/com/smeup/rpgparser/smeup/MULANGT02ConstAndDSpecTest.kt
> +     * Using %LEN on a definition inside a DIM
Should be fixed now

2024-10-16 12:28 UTC, lanarimarco approved these changes

2024-10-17 12:55 UTC, lanarimarco approved these changes

2024-10-17 12:55 UTC, merged